server.port: 8084

# Spring Config
spring:
  application:
    name: vets-service
  cache:
    cache-names: vets
  cloud:
    refresh:
      refreshable: false
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    url: jdbc:mysql://localhost:3306/petclinic?useSSL=false
    username: root
    password: petclinic
    initialization-mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: none

# Logging
logging.level.org.springframework: INFO
