server.port: 8082

# Logging
logging.level.org.springframework: INFO

# Spring Config
spring:
  application:
    name: notifications-service
  cloud:
    refresh:
      refreshable: false

kafka:
  bootstrap:
    config:
      server: "localhost:9092"

customers-service:
  url: "http://localhost:8080"
  ribbon:
    eureka:
      enabled: false
visits-service:
  url: "http://localhost:8085"
  ribbon:
    eureka:
      enabled: false
