server.port: 8080

# Logging
logging.level.org.springframework: INFO

# Spring Config
spring:
  application:
    name: notifications-service
  cloud:
    refresh:
      refreshable: false
  boot:
    admin:
      client:
        auto-deregistration: true
        url: "http://admin-server:8080"
        instance:
          prefer-ip: true

kafka:
  bootstrap:
    config:
      server: kafka-oss-cp-kafka-headless:9092

customers-service:
  url: "http://customers-service:8080"
  ribbon:
    eureka:
      enabled: false
visits-service:
  url: "http://visits-service:8080"
  ribbon:
    eureka:
      enabled: false
